export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';
export const CLEAR_POSTS = 'CLEAR_POSTS';

export const UPDATE_LIKES_REQUEST = 'UPDATE_LIKES_REQUEST';
export const UPDATE_LIKES_SUCCESS = 'UPDATE_LIKES_SUCCESS';
export const UPDATE_LIKES_FAIL = 'UPDATE_LIKES_FAIL';
