export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const UNLOAD_PROFILE = 'UNLOAD_PROFILE';

export const GET_PROFILE_BY_ID_REQUEST = 'GET_PROFILE_BY_ID_REQUEST';
export const GET_PROFILE_BY_ID_SUCCESS = 'GET_PROFILE_BY_ID_SUCCESS';
export const GET_PROFILE_BY_ID_FAIL = 'GET_PROFILE_BY_ID_FAIL';
export const GET_PROFILE_BY_ID_CLEAR = 'GET_PROFILE_BY_ID_CLEAR';

export const GET_PROFILES_REQUEST = 'GET_PROFILES_REQUEST';
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';
export const GET_PROFILES_FAIL = 'GET_PROFILES_FAIL';

export const CREATE_UPDATE_PROFILE_REQUEST = 'CREATE_UPDATE_PROFILE_REQUEST';
export const CREATE_UPDATE_PROFILE_SUCCESS = 'CREATE_UPDATE_PROFILE_SUCCESS';
export const CREATE_UPDATE_PROFILE_FAIL = 'CREATE_UPDATE_PROFILE_FAIL';

export const DELETE_EDUCATION_REQUEST = 'DELETE_EDUCATION_REQUEST';
export const DELETE_EDUCATION_SUCCESS = 'DELETE_EDUCATION_SUCCESS';
export const DELETE_EDUCATION_FAIL = 'DELETE_EDUCATION_FAIL';

export const DELETE_EXPERIENCE_REQUEST = 'DELETE_EXPERIENCE_REQUEST';
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS';
export const DELETE_EXPERIENCE_FAIL = 'DELETE_EXPERIENCE_FAIL';
