export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const GET_PROFILES_REQUEST = 'GET_PROFILES_REQUEST';
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';
export const GET_PROFILES_FAIL = 'GET_PROFILES_FAIL';
export const UNLOAD_PROFILE = 'UNLOAD_PROFILE';

export const CREATE_UPDATE_PROFILE_REQUEST = 'CREATE_UPDATE_PROFILE_REQUEST';
export const CREATE_UPDATE_PROFILE_SUCCESS = 'CREATE_UPDATE_PROFILE_SUCCESS';
export const CREATE_UPDATE_PROFILE_FAIL = 'CREATE_UPDATE_PROFILE_FAIL';
